export const MenuItems = [
    {
        title:'Home',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'Services',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'Sell',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'Buy',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'Sign-In',
        url:'#',
        cName:'nav-links-mobile'
    },
]